SELECT 
 COUNT(1) QUANTIDADE,
  TRANSLATE(UPPER(TRIM(A.DS_LIVRO)),'дацузмиайбтшсгх','AAAOUIEAEAOUOCE') AS LIVROS
 FROM TB_LIVRO B
 LEFT JOIN TB_LIVRO A ON B.CD_TEMA = A.CD_LIVRO
 GROUP BY A.DS_LIVRO
