-- TRATAMENTO DE CARACTERES 

SELECT COUNT(1)
	--TRANSLATE(UPPER(TRIM(NM_AUTOR)),'дацузмиайбтшсгх','AAAOUIEAEAOUOCE') NOME_AUTOR
FROM [dbo].[TB_AUTOR] A
-------------------------------------

-- QUERY QUAIS TEMAS POSSUEM MAIS LIVROS

SELECT 
COUNT(1) AS QUANTIDADE,
TRANSLATE(UPPER(TRIM(A.DS_TEMA)),'дацузмиайбтшсгх','AAAOUIEAEAOUOCE') AS TEMA
 FROM TB_TEMA B
 INNER JOIN TB_TEMA A ON A.DS_TEMA = B.DS_TEMA
 GROUP BY A.DS_TEMA


 SELECT 
 COUNT(1) QUANTIDADE,
  TRANSLATE(UPPER(TRIM(A.DS_LIVRO)),'дацузмиайбтшсгх','AAAOUIEAEAOUOCE') AS LIVROS
 FROM TB_LIVRO B
 LEFT JOIN TB_LIVRO A ON B.CD_TEMA = A.CD_LIVRO
 GROUP BY A.DS_LIVRO

 SELECT 
 --COUNT(1) QUANTIDADE, 
 B.DS_TEMA AS TEMA,
 COUNT(A.DS_LIVRO) AS LIVRO 
 FROM TB_TEMA B
 LEFT JOIN TB_LIVRO A ON A.DS_LIVRO = B.DS_TEMA
 GROUP BY B.DS_TEMA, A.DS_LIVRO

 SELECT * FROM [dbo].[TB_TEMA]
SELECT * FROM[dbo].[TB_LIVRO]
SELECT * FROM TB_AUTOR
-------------------------------------------------------------------
 SELECT
 TRANSLATE(UPPER(TRIM(A.NM_AUTOR)),'дацузмиайбтшсгх','AAAOUIEAEAOUOCE') AS NM_AUTOR
 FROM TB_AUTOR A
 LEFT JOIN TB_AUTOR B ON A.CD_AUTOR = B.CD_AUTOR
 GROUP BY A.NM_AUTOR