CREATE TABLE TB_AUTOR(
CD_AUTOR				INT IDENTITY(1,1)	NOT NULL,
NM_AUTOR				VARCHAR(250)		NOT NULL,
DT_INCLUSAO_REGISTRO	DATE				NOT NULL,
CONSTRAINT PK_TB_AUTOR_CD_AUTOR PRIMARY KEY CLUSTERED (CD_AUTOR)
);