CREATE TABLE TB_COMPRA(
CD_COMPRA									INT IDENTITY(1,1) 		NOT NULL,
CD_LIVRO									INT						NOT NULL,
VL_LIVRO									MONEY					NOT NULL,
DT_INCLUSAO_REGISTRO						DATE					NOT NULL,
CONSTRAINT FK_TB_COMPRA_CD_LIVRO		 	FOREIGN KEY (CD_LIVRO) 	 REFERENCES TB_LIVRO (CD_LIVRO)
);