CREATE TABLE TB_LIVRO (
CD_LIVRO								INT IDENTITY(1,1) 		NOT NULL,
DS_LIVRO								VARCHAR(350)	  		NOT NULL,
DT_PUBLICACAO							DATE					,	
CD_AUTOR								INT						NOT NULL,
CD_TEMA									INT						NOT NULL,
CD_EDITORA								INT						NOT NULL,
DT_INCLUSAO_REGISTRO					DATE					NOT NULL,
CONSTRAINT PK_TB_LIVRO_CD_LIVRO 		PRIMARY KEY CLUSTERED (CD_LIVRO),
CONSTRAINT FK_TB_LIVRO_CD_AUTOR	 	 	FOREIGN KEY (CD_AUTOR) 	 REFERENCES TB_AUTOR	(CD_AUTOR),
CONSTRAINT FK_TB_LIVRO_CD_TEMA		 	FOREIGN KEY (CD_TEMA) 	 REFERENCES TB_TEMA		(CD_TEMA),
CONSTRAINT FK_TB_LIVRO_CD_EDITORA	 	FOREIGN KEY (CD_EDITORA) REFERENCES TB_EDITORA	(CD_EDITORA)
);