CREATE TABLE TB_TEMA(
CD_TEMA					INT IDENTITY(1,1)	NOT NULL,
DS_TEMA					VARCHAR(250)		NOT NULL,
DT_INCLUSAO_REGISTRO	DATE				NOT NULL,
CONSTRAINT PK_TB_TEMA_CD_TEMA PRIMARY KEY CLUSTERED (CD_TEMA)
);