INSERT INTO TB_TEMA (DS_TEMA, DT_INCLUSAO_REGISTRO) VALUES('CIÊNCIA E TECNOLOGIA	', GETDATE());
INSERT INTO TB_TEMA (DS_TEMA, DT_INCLUSAO_REGISTRO) VALUES('HISTÓRIA	', GETDATE());
INSERT INTO TB_TEMA (DS_TEMA, DT_INCLUSAO_REGISTRO) VALUES('BIOGRAFIA	', GETDATE());
INSERT INTO TB_TEMA (DS_TEMA, DT_INCLUSAO_REGISTRO) VALUES('PSICOLOGIA	', GETDATE());
INSERT INTO TB_TEMA (DS_TEMA, DT_INCLUSAO_REGISTRO) VALUES('PORTUGUÊS	', GETDATE());
INSERT INTO TB_TEMA (DS_TEMA, DT_INCLUSAO_REGISTRO) VALUES('MATEMÁTICA	', GETDATE());
INSERT INTO TB_TEMA (DS_TEMA, DT_INCLUSAO_REGISTRO) VALUES('estatística', GETDATE());
INSERT INTO TB_TEMA (DS_TEMA, DT_INCLUSAO_REGISTRO) VALUES('auto ajuda', GETDATE());

